phrase:
  project_id: 6852a17cf276ee9290de355ad64a645e
  push:
    sources:
      - file: ./<locale_code>.json
        params:
          file_format: simple_json
          locale_code: en-US
          autotranslate: true
  pull:
    targets:
      - file: ./<locale_code>.json
        params:
          file_format: simple_json
