phrase:
  project_id: 3f7cf65c30ffeabd690ace33cad65c84
  push:
    sources:
      - file: ./<locale_code>.strings
        params:
          file_format: strings
          locale_code: en-US
          autotranslate: false
  pull:
    targets:
      - file: ./<locale_code>.strings
        params:
          file_format: strings
